@echo off
echo 🚀 Initializing AgriLink Git Repository...
git init
echo 🔗 Adding Remote Origin...
git remote add origin https://github.com/PavanWadile77/Agri-Link.git
echo 📦 Adding Files...
git add .
echo 💾 Committing Changes...
git commit -m "Initial commit: AgriLink Mobile App with Redux and Interactive Prototype"
echo 🌿 Setting Main Branch...
git branch -M main
echo ⬆️ Pushing to GitHub...
git push -u origin main
echo ✅ Upload Complete!
pause
